version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  server:
    build:
      context: .
      dockerfile: ./compose/production/server/Dockerfile

    image: setup_production_server
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env/.production/.server
      - ./.env/.production/.postgres
    command: /start
    ports:
      - "8000:8000"
    networks:
      - back-end

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: setup_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.env/.production/.postgres
    networks:
      - back-end

networks:
  back-end:
    driver: bridge
