version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  server:
    build:
      context: .
      dockerfile: ./compose/production/server/Dockerfile

    image: setup_production_server
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.server
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: setup_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
